### ISSUE TITLE
The number of log backups cannot reach the maximum value(100) of the control in the settings panel.

### ISSUE THREAD

**Issue by hwf1324** [CyrilleB79/NVDA-Dev-Test-Toolbox#13]
The number of log backups cannot reach the maximum value(100) of the control in the settings panel.

When the value is 100, the plug-in will not take effect after restarting NVDA, and 99 will.

And I don't seem to find any errors in the logs.

**Comment by CyrilleB79** [comment]
@hwf1324, thanks for reporting.
Actually (and fortunately), there is an error in the log.

**Comment by CyrilleB79** [comment]
Fixed in 50fed57478c84da60caef65b036e948de2a9935b.
