### ISSUE TITLE
TreeInterceptor not longer recognized in MS Edge (UIA=

### ISSUE THREAD

**Issue by CyrilleB79** [CyrilleB79/NVDA-Dev-Test-Toolbox#9]
[Message](https://nvda-addons.groups.io/g/nvda-addons/topic/issue_with_the_nvda_dev/92954411?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,92954411,previd%3D1660290935006827048,nextid%3D1653932167446570873&previd=1660290935006827048&nextid=1653932167446570873) from the NVDA add-on mailing list:
  > Hi dear friends,
  > 
  > First of all, I wanted to thank Cyrille for his NVDA Dev & Test Toolbox add-on.
  > 
  > When I enable this add-on, After enabling the UIA feature with Microsoft Edge, the treeInterceptor object is no longer recognized in web pages in Microsoft Edge.
  > 
  > We therefore find ourselves unable to activate or deactivate the browse mode.
  > 
  > The problem certainly comes from the way the logReader.DocumentWithLogTreeInterceptor class was dynamically assigned.
  > 
  > Kind regards,
  > Abdel.

Cc  @abdel792

Reminder for myself: see also [here](https://nvda-addons.groups.io/g/nvda-addons/topic/customize_say_all/92912189?p=,,,100,0,0,0::recentpostdate/sticky,,,100,2,0,92912189,previd%3D1660290935006827048,nextid%3D1653932167446570873&previd=1660290935006827048&nextid=1653932167446570873).

**Comment by abdel792** [comment]
Hi dear @CyrilleB79,

Don't worry, I received your comment.

I'm currently unavailable, but if you wish, I could seek a solution with you soon.

Thanks.

Kind regards,
Abdel.

**Comment by CyrilleB79** [comment]
Hi @abdel792 

You write:
> I'm currently unavailable, but if you wish, I could seek a solution with you soon.

Thanks for this proposal. If you have an idea on how to solve this, or just an explanation why there is this issue, I would be more than happy to hear from you when you are available.
For now, I do not have found the reason why I cannot switch to browse mode in Edge with this add-on.
Thanks!

**Comment by CyrilleB79** [comment]
Hello @abdel792 

I have a fix in the branch [restoreEdgeUIA](https://github.com/CyrilleB79/NVDA-Dev-Test-Toolbox/tree/restoreEdgeUIA).
Would you mind test it and confirm that all is OK for you?

Note:
Mainly, I have replaced
`super()._get_treeInterceptorClass()`
by:
`super().treeInterceptorClass`

But I do not know exactly why this fixes the issue!

**Comment by CyrilleB79** [comment]
Sorry, I had not pushed this branch.
You can test again now.
